---
name: Práctica Apl. Parcial y Orden Superior
locale: es
type: practice
beta: false
teacher_info: 
language: haskell
id_format: '%05d'
order:
- 3
- 5
- 1
- 2
- 4
- 111
- 112
- 113
- 114
- 115
- 116
- 117
